name = "OpenAIGym"
uuid = "41d6fcb8-dd24-11e8-2536-c3dc023218b5"
authors = ["Tom Breloff <tom@breloff.com>", "Joel Mason <jobba1@hotmail.com>", "Iblis Lin <iblis@hs.ntnu.edu.tw>"]
version = "0.1.0"

[deps]
MinimalRLCore = "4557a151-568a-41c4-844f-9d8069264cea"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
